/*
 * Wayfinder - build.js
 *
 * Purpose:
 * Builds the distributable Wayfinder Chrome extension from the
 * project's source files and creates the ZIP package used for release.
 *
 * Each build begins by deleting and recreating the dist/ directory so
 * previously generated extension files do not remain in a new build.
 *
 * The build process then:
 *
 * - Reads manifest.json and writes a formatted copy into dist/
 * - Copies the css/ directory into dist/css/
 * - Copies the assets/ directory into dist/assets/ when it exists
 * - Copies src/people/radar.css into dist/people/radar.css
 * - Uses esbuild to bundle the Wayfinder JavaScript application
 * - Uses src/content/content.js as the JavaScript entry point
 * - Bundles imported Wayfinder modules into dist/content.js
 * - Outputs the bundle as an IIFE targeting Chrome 120+
 * - Generates a source map for the bundled JavaScript
 *
 * After the extension has been built, this script deletes and recreates
 * the release/ directory and uses PowerShell Compress-Archive to package
 * the contents of dist/ into:
 *
 * release/Canvas_Progress_Tracker.zip
 *
 * That ZIP contains the built extension files intended for deployment
 * or upload to the Chrome Web Store.
 *
 * Important:
 * Files in dist/ and release/ are generated output. Changes should be
 * made to the source project and then regenerated by running this build
 * script rather than editing generated files directly.
 */


const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const DIST = "dist";
const RELEASE = "release";
const ZIP_NAME = "Canvas_Progress_Tracker.zip";
const ZIP_PATH = path.join(RELEASE, ZIP_NAME);

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST);

const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));

fs.writeFileSync(
  path.join(DIST, "manifest.json"),
  JSON.stringify(manifest, null, 2)
);

fs.cpSync("css", path.join(DIST, "css"), { recursive: true });

if (fs.existsSync("assets")) {
  fs.cpSync("assets", path.join(DIST, "assets"), { recursive: true });
}

const radarCssSource = path.join("src", "people", "radar.css");
const radarCssDestDir = path.join(DIST, "people");

if (fs.existsSync(radarCssSource)) {
  fs.mkdirSync(radarCssDestDir, { recursive: true });
  fs.copyFileSync(radarCssSource, path.join(radarCssDestDir, "radar.css"));
}


esbuild
  .build({
    entryPoints: ["src/content/content.js"],
    bundle: true,
    outfile: path.join(DIST, "content.js"),
    format: "iife",
    target: ["chrome120"],
    sourcemap: true,
    logLevel: "info"
  })
  .then(() => {
    fs.rmSync(RELEASE, { recursive: true, force: true });
    fs.mkdirSync(RELEASE);

    execFileSync(
      "powershell",
      [
        "-NoProfile",
        "-Command",
        `Compress-Archive -Path "${DIST}\\*" -DestinationPath "${ZIP_PATH}" -Force`
      ],
      { stdio: "inherit" }
    );

    console.log(`\n✅ Built extension: ${DIST}`);
    console.log(`✅ Created release ZIP: ${ZIP_PATH}`);
  })
  .catch(() => process.exit(1));